services:
  db:
    image: cockroachdb/cockroach:v21.2.10
    command: start-single-node --insecure --accept-sql-without-tls
    ports:
      - "26257:26257"
      - "8080:8080"
  meilisearch:
    image: getmeili/meilisearch:v0.26.1
    ports:
      - "7700:7700"
